### ISSUE TITLE
Multiple chrome instances?

### ISSUE THREAD

**Issue by drmrbrewer** [skalfyfan/dockerized-puppeteer#2]
I've got this up and running nicely... thanks very much.

Now I'm trying to go a step further... rather than just a single instance of `google-chrome`.  I thought that I could simply start two instances in `entrypoint.sh`, one with `--remote-debugging-port=9222` and another with `--remote-debugging-port=9223`, and then connect to these at `myChromeServer:9222/json/version` and `myChromeServer:9223/json/version` respectively... and `EXPOSE` both ports in the dockerfile of course.

But for the second one I get an `connect ECONNREFUSED` error... first one still works fine.

Am I barking up the wrong tree?  How should I be going about starting two instances and connecting to them separately?  I've also considered just scaling up the number of chrome containers, but then I run into [this problem](https://stackoverflow.com/q/49028742/4070848).

**Comment by sahanatroam** [comment]
@skalfyfan Yes, would be nice to know this too

**Comment by milesrichardson** [comment]
Generally you only want to run one process per container. A much better approach would be to use docker-compose to run multiple replicas of chrome, and let your app take care of picking which one to use (or build out a load balancing layer).
